# Generated by Django 5.0.3 on 2024-03-14 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Equipos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tecnico',
            name='num_camisa',
        ),
    ]
