# Generated by Django 5.0.3 on 2024-03-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipos', '0003_alter_jugador_num_camisa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha_Nacimiento'),
        ),
    ]
